### PR TITLE
Add Getting Started by Using Kotlin document and sample project

### PR DESCRIPTION
**Pull request by ymorimo**
This PR adds a document and a sample project for the Getting Started with ScalarDB by Using Kotlin to the `docs` directory.

### CODE REVIEW

**Review by josh-wong — APPROVED** [review]
LGTM! Thank you!🙇‍♂️

**Comment by josh-wong** [comment]
@ymorimo @brfrn169 Does this getting started tutorial apply to all versions from ScalarDB 3.5 onward?

**Comment by brfrn169** [comment]
I think we can apply it to all versions from ScalarDB 3.5 onward.

@ymorimo What do you think?

**Comment by ymorimo** [comment]
@josh-wong The sample app doesn't use any features that are dependent on a specific version, so I think it is applicable to ScalarDB 3.5+.

**Comment by josh-wong** [comment]
> @josh-wong The sample app doesn't use any features dependent on a specific version (since the Kotlin code was basically converted from the original Java code), so I think it applies to ScalarDB 3.5+.

@ymorimo Perfect. Thank you!

**Review by brfrn169 — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
