### PR TITLE
Cosmos DB setup steps moved to under install prerequisites

### PR DESCRIPTION
**Pull request by scalar-boney**
I think it is better to move into install prerequisites.
Install prerequisites are used in other documents also.
Otherwise, there is a chance of missing this step.

### CODE REVIEW

**Comment by feeblefakie** [comment]
@scalar-boney But I don't think it's `install`. Also, it's still mis-leading to have bullet points and h3 together.

**Comment by scalar-boney** [comment]
> @scalar-boney But I don't think it's `install`. Also, it's still mis-leading to have bullet points and h3 together.

Sorry, 
Ok I am closing this pull request.

**Comment by feeblefakie** [comment]
@scalar-boney I'm just pointing out that it's not `install` and inconsistent format.
If the doc is not well-organized, it should be fixed.

**Comment by feeblefakie** [comment]
@scalar-boney Please do something for this.

**Comment by scalar-boney** [comment]
> @scalar-boney Please do something for this.

@feeblefakie san, Document updated.
Could you please check when you get a chance?

**Comment by feeblefakie** [comment]
@scalar-boney I think the essential issue is referrer's doc because it asks uses to go back and forth several times to database-specific pages.
https://github.com/scalar-labs/getting-started-with-scalardb

Why this getting started doc executes schema-loader before configuring scalardb.properties whereas [our getting started](https://github.com/scalar-labs/scalardb/blob/master/docs/getting-started-with-scalardb.md) executes after?

**Comment by scalar-boney** [comment]
> @scalar-boney I think the essential issue is the referrer's doc because it asks uses to go back and forth several times to database-specific pages.
> https://github.com/scalar-labs/getting-started-with-scalardb
> 
> Why this getting started doc executes schema-loader before configuring scalardb.properties whereas [our getting started](https://github.com/scalar-labs/scalardb/blob/master/docs/getting-started-with-scalardb.md) executes schema-loader after scalardb.properties configuration?

Document modified accordingly.
https://github.com/scalar-labs/getting-started-with-scalardb/pull/6

@feeblefakie san, Could you please check when you get a chance?

**Pull request closed without merging**
