### PR TITLE
Fix default value of cross-partition scan in docs

### PR DESCRIPTION
**Pull request by jnmt**
## Description

This PR fixes the default value of cross-partition scan in docs.

## Related issues and/or PRs

- #1294
- #1301
- #1338

## Changes made

Fixed the default value of cross-partition scan in docs.

## Checklist

- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation to reflect the changes.
- [x] Any remaining open issues linked to this PR are documented and up-to-date (Jira, GitHub, etc.).
- [x] Tests (unit, integration, etc.) have been added for the changes.
- [x] My changes generate no new warnings.
- [x] Any dependent changes in other PRs have been merged and published.

## Additional notes (optional)

N/A

## Release notes

Fixed the default value of cross-partition scan in docs.

### CODE REVIEW

**Review by reddikih — APPROVED** [review]
LGTM! Thank you!!

**Review by josh-wong — APPROVED** [review]
LGTM! Thank you!🙇‍♂️

**Review by komamitsu — APPROVED** [review]
LGTM! 👍

**Review by Torch3333 — APPROVED** [review]
LGTM, thank you!

**Review by brfrn169 — APPROVED** [review]
LGTM! Thank you!

**Comment by brfrn169** [comment]
I'll merge this.

@yu2scalar But, please take a look when you have time!

**Pull request merged**
