### PR TITLE
Fix relational scan builder to keep ordering information and so on

### PR DESCRIPTION
**Pull request by jnmt**
This PR fixes an issue that a scan builder loses a limit, orderings, projections, and consistency specified before adding the where clause. There was no problem when specifying them "after" the where clause, though.

### CODE REVIEW

**Review by brfrn169 — APPROVED** [review]
LGTM!  Thank you!

**Review by komamitsu — APPROVED** [review]
LGTM! 👍

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Comment by jnmt** [comment]
@Torch3333 I will merge this, but PTAL when you get a chance.

**Pull request merged**
