### PR TITLE
Fix broken links to the "Getting Started" doc

### PR DESCRIPTION
**Pull request by josh-wong**
This PR fixes broken links that were not updated in the https://github.com/scalar-labs/scalardb/pull/990.

I've replaced the broken link with the link that points to [Getting Started with ScalarDB](https://github.com/scalar-labs/scalardb/blob/master/docs/getting-started-with-scalardb.md).

### CODE REVIEW

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Review by brfrn169 — APPROVED** [review]
LGTM! Thank you!

**Review by Torch3333 — APPROVED** [review]
LGTM, thank you!

**Comment by brfrn169** [comment]
@josh-wong We might have the same broken links in other ScalarDB related projects. Can you please check them as well?

**Comment by josh-wong** [comment]
@brfrn169 Thank you! You're right. I see a few other repositories that have docs mentioning the old getting started doc. I'll submit PRs to those repositories as well.

**Pull request merged**
