### PR TITLE
Backport to branch(3) : Fix a corner case issue that causes inconsistent Coordinator states when lazy recovery happens before group commit

### PR DESCRIPTION
**Pull request by feeblefakie**
Backport of https://github.com/scalar-labs/scalardb/pull/2135

### CODE REVIEW

**Comment by brfrn169** [comment]
@komamitsu Could you please take a look at the CI failures when you have time?

**Comment by komamitsu** [comment]
@brfrn169 Oh, thanks. I forgot that empty PRs are created instead of issues.

**Comment by komamitsu** [comment]
> I forgot that empty PRs are created instead of issues.

Ah, no. This was a CI failure not cherry-pick failure...

**Comment by komamitsu** [comment]
@brfrn169 The cause of the test failures was ScalarDB v3 doesn't create `coordinator.state.tx_child_ids` column while some test cases try to access it. I pushed some workaround fix.

Thanks for letting me know that.

**Pull request merged**
