### PR TITLE
Move ResultImpl to the util package

### PR DESCRIPTION
**Pull request by brfrn169**
Now that the `ResultImpl` class is not used only for the classes in the `storage` package, we should move it to the `util` package. This PR does that. Please take a look!

### CODE REVIEW

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!
I feel `util` doesn't seem to be the best place, but I'm not sure where to put it... Hmm

**Review by thongdk8 — APPROVED** [review]
LGTM! Thank you!

**Comment by brfrn169** [comment]
@feeblefakie Thank you for taking a look at this!

> I feel `util` doesn't seem to be the best place, but I'm not sure where to put it... Hmm

Correct. `util` might not be the best place, and I'm also not sure where to put it for now. At this point, we put all the commonly used classes to `util`. Since the classes in `util` are internally used, we can refactor them easily in the future. So if we get a better idea, let's refactor them at that time. Thanks.

**Comment by feeblefakie** [comment]
@brfrn169 
> Correct. util might not be the best place, and I'm also not sure where to put it for now. At this point, we put all the commonly used classes to util. Since the classes in util are internally used, we can refactor them easily in the future. So if we get a better idea, let's refactor them at that time. Thanks.

I agree! Thank you!

**Pull request merged**
