### PR TITLE
Fix warnings displayed by IntelliJ

### PR DESCRIPTION
**Pull request by brfrn169**
## Description

This PR fixes the warnings displayed by my IntelliJ.

## Related issues and/or PRs

N/A

## Changes made

- Reduce the deprecated usages
- Fix the Javadoc warnings
- Fix some other Java warnings

## Checklist

- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation to reflect the changes.
- [x] Any remaining open issues linked to this PR are documented and up-to-date (Jira, GitHub, etc.).
- [x] Tests (unit, integration, etc.) have been added for the changes.
- [x] My changes generate no new warnings.
- [x] Any dependent changes in other PRs have been merged and published.

## Additional notes (optional)

N/A

## Release notes

N/A

### CODE REVIEW

**Review by Torch3333 — APPROVED** [review]
LGTM, thank you!

**Review by komamitsu — APPROVED** [review]
LGTM! 👍

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Comment by feeblefakie** [comment]
@brfrn169 One of the CIs fail. Can you quickly check?

**Pull request merged**
