### PR TITLE
Fix to ignore empty condition set when building Scan object

### PR DESCRIPTION
**Pull request by jnmt**
This PR fixes a bug that creates an empty conjunction when building a `Scan` object. Without this fix, the query builder generates a broken SQL statement for underlying databases with the following cases.

- Scan.newBuilder().(snip).all().where(ConditionSetBuilder.andConditionSet(ImmutableSet.of()).build())
- Scan.newBuilder().(snip).all().whereAnd(ImmutableSet.of())
- Scan.newBuilder().(snip).all().whereOr(ImmutableSet.of())
- etc.

### CODE REVIEW

**Review by komamitsu — APPROVED** [review]
LGTM! 👍

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Review by Torch3333 — APPROVED** [review]
LGTM, thank you!

**Review by brfrn169 — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
