### PR TITLE
Validate contact points size in XxxxConfig to avoid "java.lang.ArrayIndexOutOfBoundsException: 0"

### PR DESCRIPTION
**Pull request by komamitsu**
When I forgot to set `scalar.db.contact_points`, I ran into `java.lang.ArrayIndexOutOfBoundsException: 0` exception. It's not so user friendly for users. This PR adds a validation to confirm if `contactPoints` isn't empty in XxxxConfig classes.

### CODE REVIEW

**Review by brfrn169 — COMMENTED** [review]
Thank you for handling this! Maybe we can add the validation to [DatabaseConfig](https://github.com/scalar-labs/scalardb/blob/1709a213defdbdc143b0bb1b2f44408eb9d65c84/core/src/main/java/com/scalar/db/config/DatabaseConfig.java) instead of the `XXXConfig`s?

**Comment by komamitsu** [comment]
@brfrn169 I first thought the idea, but found the property seemed an optional (e.g. ConsensusCommitConfig doesn't use it.) Should we treat the property as a mandatory one by changing those usages which don't set the property?

**Review by brfrn169 — APPROVED** [review]
@komamitsu Ah, correct, the property is optional. Then I think the change is fine with me. Thanks.

**Comment by komamitsu** [comment]
Another option is to create a class inheriting DatabaseConfig that treats contact points as a mandatory with a validation and make the 4 XxxxConfigs which use the property of DatabaseConfig use the new one?

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Review by Torch3333 — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
