### PR TITLE
Add a constructor to UnsatisfiedConditionException

### PR DESCRIPTION
**Pull request by brfrn169**
This PR adds a constructor to `UnsatisfiedConditionException`. Please take a look!

### CODE REVIEW

**Review by komamitsu — APPROVED** [review]
LGTM! 👍

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Comment by brfrn169** [comment]
@Torch3333 I will merge this for now. Please take a look when you get a chance!

**Review by Torch3333 — COMMENTED** [review]
LGTM, thank you!

**Pull request merged**
