### PR TITLE
Add more context to the "Getting Started with ScalarDB" doc to help users run the sample application

### PR DESCRIPTION
**Pull request by josh-wong**
## Description

This PR adds some context to the "Execute transactions and retrieve data in the basic electronic money application" section of the "Getting Started with ScalarDB" doc so that users can better follow and understand the sample application.

## Related issues and/or PRs

- https://github.com/scalar-labs/scalardb/pull/990

## Changes made

- In the "Execute transactions and retrieve data in the basic electronic money application" section, I:
  - Added an explanation about what the application can do.
  - Added headings for each type transaction that users can execute in the application.
  - Revised the wording for executing the transactions.
- I also made some minor wording changes and moved a sentence into a note block to better highlight the content.

## Testing done

I ran our docs site locally and confirmed that this doc appears as expected with the addition of headings to the section for running the sample application. 

## Checklist

- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] The documentation has been updated to reflect the changes.
- [x] Any remaining open issues linked to this PR are documented and up-to-date (Jira, GitHub, etc.).
- [x] Tests (unit, integration, etc.) have been added for the changes.
- [x] My changes generate no new warnings.
- [x] Any dependent changes in other PRs have been merged and published.

## Additional notes (optional)

None.

### CODE REVIEW

**Review by komamitsu — APPROVED** [review]
LGTM! 👍

**Review by Torch3333 — APPROVED** [review]
LGTM, thank you!

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Comment by brfrn169** [comment]
@josh-wong The Auto-PR workflow created PRs for `3.10` to `3.6`. If you want a PR for `3.5` as well, can you please create it manually? 🙇

**Comment by josh-wong** [comment]
@brfrn169 Will do. Thanks!

**Pull request merged**
