### PR TITLE
Update supported databases

### PR DESCRIPTION
**Pull request by brfrn169**
## Description

This PR updates the supported databases.

## Related issues and/or PRs

N/A

## Changes made

- Added supported databases for ScalarDB 3.12.
- Deleted supported databases for the EOL versions.

## Checklist

- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation to reflect the changes.
- [x] Any remaining open issues linked to this PR are documented and up-to-date (Jira, GitHub, etc.).
- [x] Tests (unit, integration, etc.) have been added for the changes.
- [x] My changes generate no new warnings.
- [x] Any dependent changes in other PRs have been merged and published.

## Additional notes (optional)

N/A

## Release notes

N/A

### CODE REVIEW

**Review by josh-wong — APPROVED** [review]
LGTM! Thank you!🙇‍♂️

**Review by komamitsu — APPROVED** [review]
LGTM! 👍

**Review by feeblefakie — APPROVED** [review]
LGTM!

**Comment by brfrn169** [comment]
> @brfrn169 Sorry, 3.7 is still not EOL, I think.

@feeblefakie Ah, sorry. What I meant to say was that `3.7` is currently in the `Maintenance Support Ends` phase. From a product perspective, I considered it to be EOL. What do you think?

One more question: do you think we should continue to include databases in the `Maintenance Support Ends` phase in our support database matrix?

**Comment by brfrn169** [comment]
@feeblefakie I've reverted ScalarDB 3.7 in 2b0c674c5514b79124792ec9aec7f5e88b753fbb. Please take a look again when you have time!

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
