### PR TITLE
Change some JDBC data types to proper ones

### PR DESCRIPTION
**Pull request by komamitsu**
## Description

We noticed there was room to improve some JDBC storage column types.

The current data type mapping is as follows:
| RDBMS Storage Type | ScalarDB: INT | ScalarDB: BIGINT | ScalarDB: FLOAT | ScalarDB: DOUBLE |
|----|----|----|----|----|
| Oracle | Oracle:`INT` (==`NUMBER(38)`) | `NUMBER(19)` | - | - |
| PostgreSQL | - | - | PG:`FLOAT` (==`DOUBLE PRECISION`) | PG:`DOUBLE PRECISION` |
| MySQL | - | - | MySQL:`DOUBLE` | PG:`DOUBLE` |

ScalarDB's `INT` type is larger than `BIGINT` in Oracle. Also, ScalarDB's `FLOAT` and `DOUBLE` are the same data type in PostgreSQL and MySQL.

This PR changes the data type mapping as follows:
- In Oracle, ScalarDB `INT` type is changed from `INT` (`NUMBER(38)`) to `NUMBER(10)`
- In PostgreSQL, ScalarDB `FLOAT` type is changed from `FLOAT` (`DOUBLE PRECISION`) to `REAL` (single-precision floating-point value)
- In MySQL, ScalarDB `FLOAT` type is changed from `DOUBLE` to `REAL` (single-precision floating-point value)

Indeed, we need to consider the compatibility. But @brfrn169 and I discussed it, and concluded to fix the issue as early as possible.

## Related issues and/or PRs

None

## Changes made

- Update the data type mapping logic of `com.scalar.db.storage.jdbc.RdbEngineXxxx.getDataTypeForEngine()` to align with the above description
- Update related unit tests

## Checklist

> The following is a best-effort checklist. If any items in this checklist are not applicable to this PR or are dependent on other, unmerged PRs, please still mark the checkboxes after you have read and understood each item.

- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation to reflect the changes.
- [x] Any remaining open issues linked to this PR are documented and up-to-date (Jira, GitHub, etc.).
- [x] Tests (unit, integration, etc.) have been added for the changes.
- [x] My changes generate no new warnings.
- [x] Any dependent changes in other PRs have been merged and published.

## Additional notes (optional)

None

## Release notes

Change some data types of JDBC storages:
- In Oracle, ScalarDB `INT` type is changed from `INT` (`NUMBER(38)`) to `NUMBER(10)`
- In PostgreSQL, ScalarDB `FLOAT` type is changed from `FLOAT` (`DOUBLE PRECISION`) to `REAL` (single-precision floating-point value)
- In MySQL, ScalarDB `FLOAT` type is changed from `DOUBLE` to `REAL` (single-precision floating-point value)

### CODE REVIEW

**Comment by komamitsu** [comment]
I added @jnmt as a reviewer since he is also an expert on the data type mapping thought the import table feature and so on. Thanks 🙏

**Review by brfrn169 — APPROVED** [review]
LGTM! Thank you!

**Review by Torch3333 — APPROVED** [review]
LGTM, thank you!

**Comment by komamitsu** [comment]
@jnmt Thanks for pinging me. I think you're right. The migration of ScalarDB docs are ongoing (e.g., https://github.com/scalar-labs/docs-internal-scalardb/pull/100), I'll create a PR to address that later.

**Review by jnmt — APPROVED** [review]
LGTM! Thank you!

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

@komamitsu @brfrn169 
So, isn't this backward-compatible?
What will happen if we upgrade ScalarDB from 3.12 to 3.13?
It will still use the old type mapping?

**Comment by komamitsu** [comment]
@feeblefakie In the old type mapping, we used unnecessarily large data types in the underlying RDBMS table that are not necessary for corresponding to ScalarDB types. So, those who used v3.12 and created some ScalarDB tables with these large data types should be able to upgrade to 3.13 without any migration.

> What will happen if we upgrade ScalarDB from 3.12 to 3.13?
> It will still use the old type mapping?

Yes. The underlying RDB tables created for ScalarDB v3.12 use unnecessarily large data types (e.g., double-precision floating point type for FLOAT) and they can work with v3.13 as any ScalarDB data type hasn't changed.

@brfrn169 This is my understanding. What do you think?

**Pull request merged**
