### PR TITLE
Remove unnecessary `scalardb.cosmos.database_prefix` property

### PR DESCRIPTION
**Pull request by komamitsu**
## Description

We've already [moved to the Cosmo DB emulator](https://github.com/scalar-labs/scalardb/pull/1909) for the integration tests. As a result, `scalardb.cosmos.database_prefix` is no longer needed (see https://github.com/scalar-labs/scalardb/pull/1909#pullrequestreview-2124112981). This PR removes it as a follow-up PR.

## Related issues and/or PRs

- https://github.com/scalar-labs/scalardb/pull/1909

## Changes made

- Remove implementations that use `scalardb.cosmos.database_prefix` property

## Checklist

> The following is a best-effort checklist. If any items in this checklist are not applicable to this PR or are dependent on other, unmerged PRs, please still mark the checkboxes after you have read and understood each item.

- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation to reflect the changes.
- [x] Any remaining open issues linked to this PR are documented and up-to-date (Jira, GitHub, etc.).
- [x] Tests (unit, integration, etc.) have been added for the changes.
- [x] My changes generate no new warnings.
- [x] Any dependent changes in other PRs have been merged and published.

## Additional notes (optional)

None

## Release notes

N/A

### CODE REVIEW

**Review by brfrn169 — APPROVED** [review]
LGTM! Thank you!

**Review by Torch3333 — APPROVED** [review]
LGTM, thank you!

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Comment by feeblefakie** [comment]
@komamitsu Sorry, can you fix the conflicts? 🙇

**Pull request merged**
