### PR TITLE
Change metadata of partition key and clustering key from Set to Linke…

### PR DESCRIPTION
**Pull request by brfrn169**
…dHashSet to keep the order

https://scalar-labs.atlassian.net/browse/DLT-8128

### CODE REVIEW

**Review by feeblefakie — COMMENTED** [review]
Wow, it was pretty fast !!! 👍  
Left some questions and comments

**Review by yito88 — APPROVED** [review]
LGTM!

**Review by feeblefakie — DISMISSED** [review]
LGTM! Thank you!

**Review by feeblefakie — APPROVED** [review]
Still LGTM!

**Pull request merged**
