### PR TITLE
Move OperationVisitor to a proper location (under com.scalar.database.api package)

### PR DESCRIPTION
**Pull request by brfrn169**

### CODE REVIEW

**Comment by feeblefakie** [comment]
@brfrn169 I just added reviewers by myself. Can we review this ?

**Comment by brfrn169** [comment]
Yes. Please review this. Thanks.

**Comment by brfrn169** [comment]
@feeblefakie @yito88 Thanks for reviewing this. Could you please merge it?

**Comment by feeblefakie** [comment]
@brfrn169 Thank you for the contributions ! 👍 Both are merged into master now.

**Pull request merged**
