### PR TITLE
Add the integration tests for the Cosmos DB adapter and the DynamoDB …

### PR DESCRIPTION
**Pull request by brfrn169**
…adapter to CI

https://scalar-labs.atlassian.net/browse/DLT-8128

### CODE REVIEW

**Review by feeblefakie — APPROVED** [review]
LGTM! This is Great 👍

**Comment by feeblefakie** [comment]
@yito88 It's merged but it would be great if you can take a look when you have some time.

**Comment by yito88** [comment]
LGTM! Thank you 👍

**Review by yito88 — COMMENTED** [review]
LGTM! Thank you 👍

**Pull request merged**
