### PR TITLE
Make group commit metrics log configurable

### PR DESCRIPTION
**Pull request by komamitsu**
## Description

The current metrics monitor log is output at the DEBUG level and it requires some logger configuration to show up metrics at usual log level (INFO). It would be beneficial for developers and customers if the metrics monitor logging is output at the INFO and can be enabled via GroupCommitConfig.

## Related issues and/or PRs

- https://github.com/scalar-labs/scalardb/pull/1607

## Changes made

- Add `metricsMonitorLogEnabled` in `GroupCommitConfig`
- Make `GroupCommitter` start `GroupCommitMonitor` only when the monitoring feature is enabled

## Checklist

> The following is a best-effort checklist. If any items in this checklist are not applicable to this PR or are dependent on other, unmerged PRs, please still mark the checkboxes after you have read and understood each item.

- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation to reflect the changes.
- [x] Any remaining open issues linked to this PR are documented and up-to-date (Jira, GitHub, etc.).
- [x] Tests (unit, integration, etc.) have been added for the changes.
- [x] My changes generate no new warnings.
- [x] Any dependent changes in other PRs have been merged and published.

## Additional notes (optional)

None

## Release notes

N/A (`util/groupcommit` package isn't integrated with user facing feature yet)

### CODE REVIEW

**Review by brfrn169 — APPROVED** [review]
LGTM! Thank you!

**Review by Torch3333 — APPROVED** [review]
LGTM, thank you!

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Comment by brfrn169** [comment]
@komamitsu Could you please resolve the conflict when you have time?

**Pull request merged**
