### PR TITLE
docs(fix): Revert compatibility matrix (preserving SQLite 3 column)

### PR DESCRIPTION
**Pull request by laysakura**
PR to #762 

Revert pert of #764 in favor of: https://github.com/scalar-labs/scalardb/pull/764#discussion_r1054000771

- Remove `Scalar DB 3.8` record
- Remove ❌ in `SQLite 3` columns

### CODE REVIEW

**Comment by brfrn169** [comment]
I just re-ran the Oracle integration test as the container initialization failed.

**Review by brfrn169 — APPROVED** [review]
LGTM! Thank you!

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Review by komamitsu — APPROVED** [review]
LGTM! 👍

**Review by Torch3333 — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
