### PR TITLE
Should drop namespace only when no tables are in the namespace in Schema Loader

### PR DESCRIPTION
**Pull request by brfrn169**
Currently, when Schema Loader runs with `-D`, it always tries to drop all the namespaces in the schema file. So, if a namespace has tables other than the ones in the schema file, it shows an error or drops the namespace with the tables in the namespace, depending on the storage implementations. I think Schema Loader should drop the namespace only when no tables are in the namespace. This PR fixes this issue. Please take a look!

### CODE REVIEW

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!
Making the behavior consistent is definitely the first step to go, but I feel it would probably be useful (since I do it during my development) if we have the option to delete a namespace with tables for debugging purposes.

**Review by komamitsu — APPROVED** [review]
LGTM! 👍

**Review by kota2and3kan — APPROVED** [review]
LGTM! Thank you!

**Review by Torch3333 — APPROVED** [review]
LGTM, thank you!

**Comment by brfrn169** [comment]
> Making the behavior consistent is definitely the first step to go,

@feeblefakie Correct, we should do that. I will put it into our task list. Thanks.

**Comment by brfrn169** [comment]
It's actually a bug fix, so I changed the label to `bugfix`. Also, we will include this change in `3.6.8` and `3.7.7`.

**Pull request merged**
