### PR TITLE
docs: backup & restore from SQLite

### PR DESCRIPTION
**Pull request by laysakura**
PR to #762

### CODE REVIEW

**Review by Torch3333 — APPROVED** [review]
LGTM, thank you!

**Comment by brfrn169** [comment]
@laysakura Sorry, I didn't tell you it, but can you please merge your PR after all the reviewers approves it?

**Review by brfrn169 — COMMENTED** [review]
LGTM! Thank you!

**Comment by brfrn169** [comment]
@feeblefakie @komamitsu Can you please take a look this PR, it's already merged though.

**Review by komamitsu — COMMENTED** [review]
LGTM, thank you!

**Pull request merged**
