### PR TITLE
Update supported Java version in getting started

### PR DESCRIPTION
**Pull request by kota2and3kan**
This PR updates the description of the supported Java version in the getting started guide.

In the previous getting started guide, we built ScalarDB itself in that steps. So, we must use Java 8 to build ScalarDB.
However, in the current getting started guide, we can use `Java 8 or higher` since it gets pre-compiled ScalarDB from the Maven repository.

And, I think there is a possibility that the current description may mislead users that `ScalarDB only supports Java 8`.
(Actually, I got a such question from a user.)
So, I think it is better to describe `Java 8 or higher` in the getting started guide.

Also, Gradle 7.1 doesn't support Java 17 or higher.
So, I updated the Gradle version of the getting started project to 7.6 (current latest version).
https://docs.gradle.org/current/userguide/compatibility.html

Please take a look!

### CODE REVIEW

**Review by brfrn169 — APPROVED** [review]
LGTM! Thank you!

**Review by komamitsu — APPROVED** [review]
LGTM! Thank you!

**Review by Torch3333 — APPROVED** [review]
LGTM, thank you!

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Comment by feeblefakie** [comment]
@kota2and3kan Sorry, can you fix the conflict?

**Comment by kota2and3kan** [comment]
@feeblefakie
Thank you for your review!
I will fix the conflict. And after that, I will merge this PR.

**Pull request merged**
