### PR TITLE
Change hard-coded password for Oracle user in JDBC adapter

### PR DESCRIPTION
**Pull request by brfrn169**
## Description

This PR changes the hard-coded password for the Oracle user to a more secure one in the JDBC adapter. The primary goal of this change is to avoid violating password policies.

## Related issues and/or PRs

N/A

## Changes made

- Changed the hard-coded password for the Oracle user to a more secure one in the JDBC adapter.

## Checklist

- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation to reflect the changes.
- [x] Any remaining open issues linked to this PR are documented and up-to-date (Jira, GitHub, etc.).
- [x] Tests (unit, integration, etc.) have been added for the changes.
- [x] My changes generate no new warnings.
- [x] Any dependent changes in other PRs have been merged and published.

## Additional notes (optional)

N/A

## Release notes

Changed the hard-coded password for the Oracle user to a more secure one in the JDBC adapter.

### CODE REVIEW

**Review by kota2and3kan — APPROVED** [review]
LGTM! Thank you!

---

FYI:

I checked the `minimum default password complexity rules` of Autonomous Database.
https://docs.oracle.com/en/cloud/paas/autonomous-database/serverless/adbsb/manage-users-create.html#GUID-72DFAF2A-C4C3-4FAC-A75B-846CC6EDBA3F

1. The password must be between 12 and 30 characters long and must include at least one uppercase letter, one lowercase letter, and one numeric character.
   Note, the password limit is shown as 60 characters in some help tooltip popups. Limit passwords to a maximum of 30 characters.
1. The password cannot contain the username.
1. The password cannot be one of the last four passwords used for the same username.
1. The password cannot contain the double quote (") character.
1. The password must not be the same password that is set less than 24 hours ago.

Regarding `1.`, I think we can pass this limitation by the fixes of this PR.

However, regarding `2.`, `3.`, and `5.`, I guess there might be a possibility that some issue occurs. (e.g., if users create a user (i.e., namespace in ScalarDB) `foo` and drop the user `foo` and re-create the same user `foo`, it will violate the limitation `3.`.)

So, as we discussed in the previous meeting, it might be better to add a new feature like `users can set arbitrary passwords` in the future.

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Review by komamitsu — APPROVED** [review]
LGTM! 👍

**Review by Torch3333 — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
