### PR TITLE
Make the ConsensusCommitAdmin only return transaction table

### PR DESCRIPTION
**Pull request by Torch3333**
This PR updates the `ConsensusCommitAdmin.getTableMetadata()` and `ConsensusCommitAdmin.getNamespaceTableNames()` to only return transaction tables. Up until now, storage tables were also returned.

### CODE REVIEW

**Review by brfrn169 — APPROVED** [review]
LGTM! Thank you!

Are you going to do things to hide coordinator tables from users in another PR?

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Comment by brfrn169** [comment]
> Are you going to do things to hide coordinator tables from users in another PR?

@Torch3333 What about this?

**Comment by Torch3333** [comment]
> > Are you going to do things to hide coordinator tables from users in another PR?
> 
> @Torch3333 What about this?

Since the coordinator table is non-transactional, the current code does not return the coordinator table information: 
- `ConsensusCommitAdmin.getTableMetadata(coordinatorNamespace, coordinatorTable)` will return `null` 
- `ConsensusCommitAdmin.getNamespaceTableNames(coordinatorNamespace)` will return an empty Set

**Comment by brfrn169** [comment]
@Torch3333 Ah, that's right. Thank you!

**Pull request merged**
