### PR TITLE
Fix to prevent scan with index after overlapping put

### PR DESCRIPTION
**Pull request by jnmt**
## Description

This PR prevents a scan with an index key after the overlapping put, similar to the cross-partition scan, since we currently miss the check. Without this fix, users may be able to see inconsistent index scan results after putting related records. The checking policy is the same as the cross-partition scan explained in https://github.com/scalar-labs/scalardb/pull/900#discussion_r1228908653 (we need to check if the index key is overlapped instead of arbitrary conditions).

## Related issues and/or PRs

- #900

## Changes made

- Adds an overlapping check for an index scan and a write set.

## Checklist

- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation to reflect the changes.
- [x] Any remaining open issues linked to this PR are documented and up-to-date (Jira, GitHub, etc.).
- [x] Tests (unit, integration, etc.) have been added for the changes.
- [x] My changes generate no new warnings.
- [x] Any dependent changes in other PRs have been merged and published.

## Additional notes (optional)

N/A

## Release notes

Fixed a bug where users could see inconsistent results when scanning records by an index key after putting the related records in Consensus Commit transactions.

### CODE REVIEW

**Review by komamitsu — APPROVED** [review]
LGTM! 👍

**Review by Torch3333 — APPROVED** [review]
LGTM, thank you!

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Review by brfrn169 — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
