### PR TITLE
Remove ScalarDB Server

### PR DESCRIPTION
**Pull request by brfrn169**
## Description

This PR removes ScalarDB Server related things.

## Related issues and/or PRs

N/A

## Changes made

- Removed ScalarDB Server related files.
- Removed ScalarDB Server things from the GitHub actions workflow.

## Checklist

- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation to reflect the changes.
- [x] Any remaining open issues linked to this PR are documented and up-to-date (Jira, GitHub, etc.).
- [x] Tests (unit, integration, etc.) have been added for the changes.
- [x] My changes generate no new warnings.
- [x] Any dependent changes in other PRs have been merged and published.

## Additional notes (optional)

N/A

## Release notes

N/A

### CODE REVIEW

**Review by Torch3333 — APPROVED** [review]
LGTM, thank you!

**Comment by komamitsu** [comment]
@brfrn169 https://github.com/scalar-labs/scalardb/blob/29a7721c6093a27a4eb3584c4f15a5e506052843/core/src/test/java/com/scalar/db/config/DatabaseConfigTest.java still contains a few test cases for `grpc`. They can be also removed?

**Comment by brfrn169** [comment]
> @brfrn169 https://github.com/scalar-labs/scalardb/blob/29a7721c6093a27a4eb3584c4f15a5e506052843/core/src/test/java/com/scalar/db/config/DatabaseConfigTest.java still contains a few test cases for `grpc`. They can be also removed?

@komamitsu Good catch! Fixed in 6518c9eee99bb58f4b8e40e05adf6575556a1556. Thanks.

**Review by komamitsu — APPROVED** [review]
LGTM! 👍

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Review by kota2and3kan — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
