### PR TITLE
Add description how to build docker image of ScalarDB Server

### PR DESCRIPTION
**Pull request by kota2and3kan**
I was not able to find the description of how to build a Docker image of ScalarDB Server from the source code.
From the perspective of customers/users, there is no problem since they can get the docker image from Github Packages or each marketplace.
However, from the perspective of developers (mainly new development members), I think this is useful information.
So, I added it to the document. Please take a look!

### CODE REVIEW

**Review by komamitsu — APPROVED** [review]
Thanks! LGTM.

But how about using a similar guide to https://github.com/scalar-labs/scalardb/blob/master/docs/schema-loader.md#build ? Either content is fine with me, but unified something would be better.

**Review by brfrn169 — APPROVED** [review]
LGTM! Thank you!

**Comment by kota2and3kan** [comment]
@komamitsu  
Thank you for your review!
Please let me confirm the details of your suggestion.

> But how about using a similar guide to https://github.com/scalar-labs/scalardb/blob/master/docs/schema-loader.md#build ? Either content is fine with me, but unified something would be better.

Do you mean it is better to update the table of contents like the following?

* Table of contents (example)
  ```
  # Scalar DB Server
  ## Usage
  ### Install
  ### Build
  ### Docker
  ### Run
  #### Configure Scalar DB Server
  #### Start Scalar DB Server
  #### Zip archives
  #### Usage of the Java client of Scalar DB Server
  ## Further reading
  ```

If yes, I agree with you since the unified structure document is readable for users.
And, I will update it in this PR.

**Comment by komamitsu** [comment]
@kota2and3kan Oops, I pasted the wrong URL. I should've put https://github.com/scalar-labs/scalardb/blob/master/docs/schema-loader.md#docker. I also just noticed it would make no sense if we unify partial formats without taking care of the whole table of content when I read your comment. I think it's too much to ask you to restructure the table of content. Please ignore my above comment. Sorry for the confusion.

**Comment by kota2and3kan** [comment]
@komamitsu  
> Oops, I pasted the wrong URL. I should've put https://github.com/scalar-labs/scalardb/blob/master/docs/schema-loader.md#docker.

Ah, I see. I understand.

> I also just noticed it would make no sense if we unify partial formats without taking care of the whole table of content when I read your comment. I think it's too much to ask you to restructure the table of content. Please ignore my above comment. Sorry for the confusion.

OK. No problem!

**Review by Torch3333 — APPROVED** [review]
LGTM, thank you.

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
