### PR TITLE
Change default value of metadata cache expiration time

### PR DESCRIPTION
**Pull request by brfrn169**
## Description

This PR changes the default value of the metadata cache expiration time (`scalar.db.metadata.cache_expiration_time_secs`) to 60 seconds. Strictly speaking, this may be an incompatible change, but I don't expect it to cause any problems. If there are any objections, please let me know.

## Related issues and/or PRs

N/A

## Changes made

- Changed the default value of the metadata cache expiration time (`scalar.db.metadata.cache_expiration_time_secs`) to 60 seconds.

## Checklist

- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation to reflect the changes.
- [x] Any remaining open issues linked to this PR are documented and up-to-date (Jira, GitHub, etc.).
- [x] Tests (unit, integration, etc.) have been added for the changes.
- [x] My changes generate no new warnings.
- [x] Any dependent changes in other PRs have been merged and published.

## Additional notes (optional)

N/A

## Release notes

Changed the default value of the metadata cache expiration time (`scalar.db.metadata.cache_expiration_time_secs`) to 60 seconds.

### CODE REVIEW

**Review by kota2and3kan — APPROVED** [review]
LGTM! Thank you!

**Review by jnmt — APPROVED** [review]
LGTM! Thank you! I think this could reduce a chance that developer's face troubles when they change the schema in short term.

**Review by komamitsu — APPROVED** [review]
LGTM! 💯 💯 💯

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Comment by brfrn169** [comment]
@Torch3333 I'll merge this. Please take a look when you are back.

**Pull request merged**
