### PR TITLE
Clarify the supported Oracle JDK and OpenJDK versions; add a note about other JDKs and versions

### PR DESCRIPTION
**Pull request by josh-wong**
## Description

This PR clarifies the supported Oracle JDK and OpenJDK versions and adds a related note about other JDKs and versions.

## Related issues and/or PRs

Related to https://github.com/scalar-labs/scalardb-samples/pull/49#discussion_r1325274744

## Changes made

- Revised the supported JDKs to include LTS versions 8, 11, and 17.
- Added a note that:
  - Recommends using these LTS versions and that non-LTS versions might work.
  - Other JDKs should work, but they haven't been tested.

## Branches this PR applies to

- `master`
- `3.10`
- `3.9`
- `3.8`
- `3.7`
- `3.6`
- `3.5`

## Testing done

I ran our docs site locally with these changes and confirmed that these revised docs, including notice blocks and formatting, appeared as expected. Attached are screenshots of the two docs as they appears on the docs site.

> **Note**
>
> The two screenshots below include the same contents for this section on both pages.

**getting-started-with-scalardb.md**

JDK prerequisites getting-started-with-scalardb

**getting-started-with-scalardb-by-using-kotlin.md**

JDK prerequisites for getting-started-with-scalardb-by-using-kotlin

## Checklist

- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation to reflect the changes.
- [x] Any remaining open issues linked to this PR are documented and up-to-date (Jira, GitHub, etc.).
- [x] Tests (unit, integration, etc.) have been added for the changes.
- [x] My changes generate no new warnings.
- [x] Any dependent changes in other PRs have been merged and published.

## Additional notes (optional)

N/A

### CODE REVIEW

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Review by choplin — APPROVED** [review]
LGTM! 

Also, I'm wondering this rule (that is, the LTS version of Oracle JDK and OpenJDK are supported) should be applied to other products. If so, this would be noted in the team-handbook as our standard policy for the products, IMO.

**Review by Torch3333 — APPROVED** [review]
LGTM, thank you!

**Review by komamitsu — APPROVED** [review]
LGTM, thank you!

**Review by brfrn169 — APPROVED** [review]
LGTM! Thank you!

**Comment by josh-wong** [comment]
> Also, I'm wondering this rule (that is, the LTS version of Oracle JDK and OpenJDK are supported) should be applied to other products. If so, this would be noted in the team-handbook as our standard policy for the products, IMO.

@choplin I agree. Maybe we can add it to the Java coding guidelines page in the team handbook?

**Pull request merged**
