### PR TITLE
Fix ScanBuilder bug

### PR DESCRIPTION
**Pull request by brfrn169**
I encountered a bug where ScanBuilder doesn't create a proper `ScanAll` instance when we call `projection()`/`projections()`/`ordering()`/`orderings()`/`limit()`/`consistency()` before calling `where()`. I'll add inline comments for the details. Please take a look!

### CODE REVIEW

**Review by jnmt — APPROVED** [review]
LGTM! Thank you for the fix. It's my mad. I should have added more tests and noticed it when fixing a similar bug before.

**Review by komamitsu — APPROVED** [review]
LGTM! 👍

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Review by Torch3333 — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
