### PR TITLE
Fix broken links in supported databases doc

### PR DESCRIPTION
**Pull request by josh-wong**
## Description

This PR fixes broken links in the ScalarDB supported databases doc.

## Related issues and/or PRs

N/A

## Changes made

Fixed two broken links.

## Checklist

> The following is a best-effort checklist. If any items in this checklist are not applicable to this PR or are dependent on other, unmerged PRs, please still mark the checkboxes after you have read and understood each item.

- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation to reflect the changes.
- [x] Any remaining open issues linked to this PR are documented and up-to-date (Jira, GitHub, etc.).
- [x] Tests (unit, integration, etc.) have been added for the changes.
- [x] My changes generate no new warnings.
- [x] Any dependent changes in other PRs have been merged and published.

## Additional notes (optional)

N/A

## Release notes

N/A

### CODE REVIEW

**Review by komamitsu — APPROVED** [review]
LGTM! 👍

**Review by brfrn169 — APPROVED** [review]
LGTM! Thank you!

**Comment by brfrn169** [comment]
@josh-wong Can you please set projects you want to back port this to this PR?

**Comment by josh-wong** [comment]
> @josh-wong Can you please set projects you want to back port this to this PR?

@brfrn169 No problem. I just set the projects🙇🏻‍♂️

**Pull request merged**
