### PR TITLE
fix: DynamoAdmin.namespaceExists to check full namespace (not prefix)

### PR DESCRIPTION
**Pull request by laysakura**
Fixes: #784

### CODE REVIEW

**Review by Torch3333 — APPROVED** [review]
Good catch. LGTM, thank you.

**Review by komamitsu — APPROVED** [review]
LGTM! 👍

**Review by feeblefakie — APPROVED** [review]
Good catch! Thank you!

**Review by brfrn169 — APPROVED** [review]
Good catch! LGTM! Thank you!

**Pull request merged**
