### PR TITLE
Update scalar-schema tool to exit with status 1 if errors in CLI options

### PR DESCRIPTION
**Pull request by ymorimo**
In case of an error in the scalar-schema CLI options, it should fail with an exit status other than `0`.

It is needed to notify tools like Ansible and Terraform of the result of the scalar-schema tool.
For example, if the argument for the `--region` option is missing, it should fail with a status other than `0` to tell Terraform to abort.
The following case should not complete successfully.

```
module.scalardl.module.scalardl_blue.module.scalardl_provision.null_resource.scalardl_schema[0] (remote-exec): ERROR: ["Missing required argument for \"--region REGION\""]
...
module.scalardl.module.scalardl_blue.module.scalardl_provision.null_resource.scalardl_schema[0]: Creation complete after 8s [id=5751361347562494241]
```

https://scalar-labs.atlassian.net/browse/DLT-7415

### CODE REVIEW

**Comment by feeblefakie** [comment]
@ymorimo Seems like it's got a conflict after Yuji's refactoring. Please fix 🙇

**Comment by yito88** [comment]
@ymorimo @feeblefakie Sorry, my refactoring wasn't verified well. It works on only DynamoDB. That's because I verified it with the old binary... 🙇 I'll test and fix it. I guess it is better for you to fix this PR after that.

**Review by yito88 — APPROVED** [review]
LGTM! Thank you!

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
