### PR TITLE
Change relative docs links to docs site links in README

### PR DESCRIPTION
**Pull request by josh-wong**
## Description

This PR updates links to the docs listed in the README to point to the docs site instead of GitHub.

## Related issues and/or PRs

N/A

## Changes made

- Changed relative links to the docs on GitHub to links to the docs site.

## Checklist

> The following is a best-effort checklist. If any items in this checklist are not applicable to this PR or are dependent on other, unmerged PRs, please still mark the checkboxes after you have read and understood each item.

- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation to reflect the changes.
- [x] Any remaining open issues linked to this PR are documented and up-to-date (Jira, GitHub, etc.).
- [x] Tests (unit, integration, etc.) have been added for the changes.
- [x] My changes generate no new warnings.
- [x] Any dependent changes in other PRs have been merged and published.

## Additional notes (optional)

N/A

## Release notes

N/A

### CODE REVIEW

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Review by brfrn169 — APPROVED** [review]
LGTM! Thank you!

@josh-wong Do you want to apply this change to release and support branches?

**Comment by josh-wong** [comment]
@brfrn169 
> LGTM! Thank you!
> 
> @josh-wong Do you want to apply this change to release and support branches?

Ah yes, that would be helpful!

I've just added the projects for the versions that are currently still under Maintenance Support. Is that OK?

**Comment by brfrn169** [comment]
@josh-wong Yes, that should be okay. Thanks!

**Pull request merged**
