### PR TITLE
Fix NullPointerException when table is not found in Consensus Commit

### PR DESCRIPTION
**Pull request by brfrn169**
## Description

This PR fixes a bug where `NullPointerException` when a table specified in a Get/Scan object is not found in Consensus Commit.

The `NullPointerException` we encountered is as follows:

```java
java.lang.NullPointerException
        at com.scalar.db.transaction.consensuscommit.CrudHandler.prepareStorageSelection(CrudHandler.java:303) ~[scalardb-3.13.1-SNAPSHOT.jar:?]
        at com.scalar.db.transaction.consensuscommit.CrudHandler.scanInternal(CrudHandler.java:139) ~[scalardb-3.13.1-SNAPSHOT.jar:?]
        at com.scalar.db.transaction.consensuscommit.CrudHandler.scan(CrudHandler.java:124) ~[scalardb-3.13.1-SNAPSHOT.jar:?]
        at com.scalar.db.transaction.consensuscommit.ConsensusCommit.scan(ConsensusCommit.java:92) ~[scalardb-3.13.1-SNAPSHOT.jar:?]
        at com.scalar.db.common.DecoratedDistributedTransaction.scan(DecoratedDistributedTransaction.java:78) ~[scalardb-3.13.1-SNAPSHOT.jar:?]
        at com.scalar.db.common.TransactionDecorationDistributedTransactionManager$StateManagedTransaction.scan(TransactionDecorationDistributedTransactionManager.java:86) ~[scalardb-3.13.1-SNAPSHOT.jar:?]
        at com.scalar.db.common.DecoratedDistributedTransaction.scan(DecoratedDistributedTransaction.java:78) ~[scalardb-3.13.1-SNAPSHOT.jar:?]
        at com.scalar.db.common.DecoratedDistributedTransaction.scan(DecoratedDistributedTransaction.java:78) ~[scalardb-3.13.1-SNAPSHOT.jar:?]
        at com.scalar.db.common.ActiveTransactionManagedDistributedTransactionManager$ActiveTransaction.scan(ActiveTransactionManagedDistributedTransactionManager.java:115) ~[scalardb-3.13.1-SNAPSHOT.jar:?]
        at com.scalar.db.sql.directmode.volcanoiterator.ScanOperator.scan(ScanOperator.java:97) ~[scalardb-sql-direct-mode-3.13.1-SNAPSHOT.jar:?]
        at com.scalar.db.sql.directmode.volcanoiterator.ScanOperator.next(ScanOperator.java:71) ~[scalardb-sql-direct-mode-3.13.1-SNAPSHOT.jar:?]
        at com.scalar.db.sql.directmode.volcanoiterator.ProjectionOperator.next(ProjectionOperator.java:87) ~[scalardb-sql-direct-mode-3.13.1-SNAPSHOT.jar:?]
        at com.scalar.db.sql.directmode.DmlStatementExecutor.createResultSet(DmlStatementExecutor.java:159) ~[scalardb-sql-direct-mode-3.13.1-SNAPSHOT.jar:?]
        at com.scalar.db.sql.directmode.DmlStatementExecutor.visit(DmlStatementExecutor.java:76) ~[scalardb-sql-direct-mode-3.13.1-SNAPSHOT.jar:?]
        at com.scalar.db.sql.directmode.DmlStatementExecutor.visit(DmlStatementExecutor.java:36) ~[scalardb-sql-direct-mode-3.13.1-SNAPSHOT.jar:?]
        at com.scalar.db.sql.directmode.plan.SelectPlan.accept(SelectPlan.java:33) ~[scalardb-sql-direct-mode-3.13.1-SNAPSHOT.jar:?]
        at com.scalar.db.sql.directmode.DmlStatementExecutor.execute(DmlStatementExecutor.java:52) ~[scalardb-sql-direct-mode-3.13.1-SNAPSHOT.jar:?]
        at com.scalar.db.sql.directmode.StatementExecutor.lambda$executeDmlStatement$0(StatementExecutor.java:279) ~[scalardb-sql-direct-mode-3.13.1-SNAPSHOT.jar:?]
        at com.scalar.db.sql.directmode.DirectModeSqlTransactionManager.executeTransaction(DirectModeSqlTransactionManager.java:175) ~[scalardb-sql-direct-mode-3.13.1-SNAPSHOT.jar:?]
        at com.scalar.db.sql.directmode.StatementExecutor.executeDmlStatement(StatementExecutor.java:278) ~[scalardb-sql-direct-mode-3.13.1-SNAPSHOT.jar:?]
        at com.scalar.db.sql.directmode.StatementExecutor.visit(StatementExecutor.java:254) ~[scalardb-sql-direct-mode-3.13.1-SNAPSHOT.jar:?]
        at com.scalar.db.sql.directmode.StatementExecutor.visit(StatementExecutor.java:62) ~[scalardb-sql-direct-mode-3.13.1-SNAPSHOT.jar:?]
        at com.scalar.db.sql.statement.SelectStatement.accept(SelectStatement.java:209) ~[scalardb-sql-3.13.1-SNAPSHOT.jar:?]
        at com.scalar.db.sql.directmode.StatementExecutor.execute(StatementExecutor.java:113) ~[scalardb-sql-direct-mode-3.13.1-SNAPSHOT.jar:?]
        at com.scalar.db.sql.directmode.DirectModeSqlTransactionManager.execute(DirectModeSqlTransactionManager.java:129) ~[scalardb-sql-direct-mode-3.13.1-SNAPSHOT.jar:?]
        at com.scalar.db.sql.SqlStatementExecutable.execute(SqlStatementExecutable.java:48) ~[scalardb-sql-3.13.1-SNAPSHOT.jar:?]
        at com.scalar.db.cluster.node.sql.LocalSqlTransactionService.lambda$execute$2(LocalSqlTransactionService.java:87) ~[scalardb-cluster-node-3.13.1-SNAPSHOT.jar:?]
        at com.scalar.db.cluster.auth.AuthExecutionUtils.setAuthTokenAndExecute(AuthExecutionUtils.java:42) ~[scalardb-cluster-auth-3.13.1-SNAPSHOT.jar:?]
        at com.scalar.db.cluster.node.sql.LocalSqlTransactionService.execute(LocalSqlTransactionService.java:72) ~[scalardb-cluster-node-3.13.1-SNAPSHOT.jar:?]
        at com.scalar.db.cluster.node.sql.LocalSqlTransactionService.lambda$execute$4(LocalSqlTransactionService.java:121) ~[scalardb-cluster-node-3.13.1-SNAPSHOT.jar:?]
        at com.scalar.db.cluster.node.sql.LocalSqlTransactionService.perform(LocalSqlTransactionService.java:183) ~[scalardb-cluster-node-3.13.1-SNAPSHOT.jar:?]
        ... 15 more
```

## Related issues and/or PRs

N/A

## Changes made

- Throw `IllegalArgumentException` when the table specified in a Get/Scan object is not found.

## Checklist

- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation to reflect the changes.
- [x] Any remaining open issues linked to this PR are documented and up-to-date (Jira, GitHub, etc.).
- [x] Tests (unit, integration, etc.) have been added for the changes.
- [x] My changes generate no new warnings.
- [x] Any dependent changes in other PRs have been merged and published.

## Additional notes (optional)

N/A

## Release notes

Fixed a bug where `NullPointerException` when a table specified in a Get/Scan object is not found in Consensus Commit.

### CODE REVIEW

**Review by komamitsu — APPROVED** [review]
LGTM, thank you!

**Review by Torch3333 — APPROVED** [review]
LGTM, thank you!

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Review by kota2and3kan — APPROVED** [review]
LGTM! Thank you!

FYI: I was able to see the correct error message in my local environment.

**Pull request merged**
