### PR TITLE
docs: write about `busy_timeout` parameter for JDBC SQLite storage

### PR DESCRIPTION
**Pull request by laysakura**
As described in https://github.com/scalar-labs/scalardb/pull/819#discussion_r1161205858

### CODE REVIEW

**Review by brfrn169 — APPROVED** [review]
LGTM! Thank you!

**Review by Torch3333 — APPROVED** [review]
LGTM, thank you!

**Review by komamitsu — APPROVED** [review]
LGTM! 👍

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
